StartupEvents.registry('block', event => {
   
   
    event.create('aluminum_casing') // Create a new block
      .displayName('Aluminum Casing') // Set a custom name
      .soundType('wood') // Set a material (affects the sounds and some properties)
      .hardness(1.0) // Set hardness (affects mining time)
      .resistance(1.0) // Set resistance (to explosions, etc)
      //.tagBlock('my_custom_tag') // Tag the block with `#minecraft:my_custom_tag` (can have multiple tags)
      .requiresTool(false) // Requires a tool or it won't drop (see tags below)
      //.tagBlock('my_namespace:my_other_tag') // Tag the block with `#my_namespace:my_other_tag`
      .tagBlock('minecraft:mineable/axe') //can be mined faster with an axe
      .tagBlock('minecraft:mineable/pickaxe') // or a pickaxe
      //.tagBlock('minecraft:needs_iron_tool') // the tool tier must be at least iron
  
    event.create('aluminum_gravel')
        .displayName('Aluminum Gravel')
        .soundType('gravel')
        .hardness(1.0)
        .resistance(1.0)
        .requiresTool(false)
        .tagBlock('minecraft:mineable/shovel')

      event.create('desh_casing')
      .displayName('Desh Casing')
      .soundType('metal')
      .hardness(1.0)
      .resistance(1.0)
      .requiresTool(false)
      .tagBlock('minecraft:mineable/pickaxe')
      .tagBlock('minecraft:mineable/axe')
  
    event.create('bewitched_gravel')
      .displayName('Bewitched Gravel')
      .soundType('gravel')
      .hardness(1.0)
      .resistance(1.0)
      .requiresTool(false)
      .tagBlock('minecraft:mineable/shovel')

      event.create('oil_gravel')
      .displayName('Oil Gravel')
      .soundType('gravel')
      .hardness(1.0)
      .resistance(1.0)
      .requiresTool(false)
      .tagBlock('minecraft:mineable/shovel')

      event.create('moon_gravel')
      .displayName('Moon Gravel')
      .soundType('gravel')
      .hardness(1.0)
      .resistance(1.0)
      .requiresTool(false)
      .tagBlock('minecraft:mineable/shovel')

      event.create('martian_gravel')
      .displayName('Martian Gravel')
      .soundType('gravel')
      .hardness(1.0)
      .resistance(1.0)
      .requiresTool(false)
      .tagBlock('minecraft:mineable/shovel')

      event.create('titanium_gravel')
      .displayName('Titanium Gravel')
      .soundType('gravel')
      .hardness(1.0)
      .resistance(1.0)
      .requiresTool(false)
      .tagBlock('minecraft:mineable/shovel')

    event.create('steel_casing')
      .displayName('Steel Casing')
      .soundType('wood')
      .hardness(1.0)
      .resistance(1.0)
      .requiresTool(false)
      .tagBlock('minecraft:mineable/pickaxe')
      .tagBlock('minecraft:mineable/axe')

      event.create('obsidian_steel_casing')
      .displayName('Obsidian Steel Casing')
      .soundType('metal')
      .hardness(1.0)
      .resistance(1.0)
      .requiresTool(false)
      .tagBlock('minecraft:mineable/pickaxe')
      .tagBlock('minecraft:mineable/axe')

      event.create('tree_rubber_block')
        .displayName('Tree Rubber Block')
        .soundType('wool')
        .hardness(2.0)
        .resistance(2.0)
        .requiresTool(false)
        .tagBlock('minecraft:mineable/shovel')
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:mineable/axe')

      event.create('redstone_alloy_block')
      .displayName('Redstone Alloy Block')
      .soundType('metal')
      .hardness(2.0)
      .resistance(2.0)
      .requiresTool(false)
      .tagBlock('minecraft:mineable/pickaxe')

      event.create('desh_pressing_controller')
      .displayName('Desh Pressing Machine Controller')
      .soundType('metal')
      .hardness(2.0)
      .resistance(2.0)
      .requiresTool(false)
      .tagBlock('minecraft:mineable/pickaxe')

      event.create('desh_machine_casing')
      .displayName('Desh Machine Casing')
      .soundType('metal')
      .hardness(2.0)
      .resistance(2.0)
      .requiresTool(false)
      .tagBlock('minecraft:mineable/pickaxe')

      event.create('desh_incomplete_machine_controller')
      .soundType('metal')
      .hardness(2.0)
      .resistance(2.0)
      .requiresTool(false)
      .tagBlock('minecraft:mineable/pickaxe')

      event.create('desh_mixing_controller')
      .soundType('metal')
      .hardness(2.0)
      .resistance(2.0)
      .requiresTool(false)
      .tagBlock('minecraft:mineable/pickaxe')

      event.create('desh_washing_controller')
      .soundType('metal')
      .hardness(2.0)
      .resistance(2.0)
      .requiresTool(false)
      .tagBlock('minecraft:mineable/pickaxe')

      event.create('desh_compacting_controller')
      .soundType('metal')
      .hardness(2.0)
      .resistance(2.0)
      .requiresTool(false)
      .tagBlock('minecraft:mineable/pickaxe')

      event.create('desh_vent_casing')
      .displayName('Desh Vent Casing')
      .soundType('metal')
      .hardness(2.0)
      .resistance(2.0)
      .requiresTool(false)
      .tagBlock('minecraft:mineable/pickaxe')

      event.create('desh_gear_casing')
      .displayName('Desh Gear Casing')
      .soundType('metal')
      .hardness(2.0)
      .resistance(2.0)
      .requiresTool(false)
      .tagBlock('minecraft:mineable/pickaxe')

      event.create('desh_machine_item_input')
      .soundType('metal')
      .hardness(2.0)
      .resistance(2.0)
      .requiresTool(false)
      .tagBlock('minecraft:mineable/pickaxe')

      event.create('desh_machine_item_output')
      .soundType('metal')
      .hardness(2.0)
      .resistance(2.0)
      .requiresTool(false)
      .tagBlock('minecraft:mineable/pickaxe')

      event.create('desh_machine_fluid_input')
      .soundType('metal')
      .hardness(2.0)
      .resistance(2.0)
      .requiresTool(false)
      .tagBlock('minecraft:mineable/pickaxe')

      event.create('desh_machine_fluid_output')
      .soundType('metal')
      .hardness(2.0)
      .resistance(2.0)
      .requiresTool(false)
      .tagBlock('minecraft:mineable/pickaxe')

      event.create('desh_logistic_casing')
      .displayName('Desh Logistic Casing')
      .soundType('metal')
      .hardness(2.0)
      .resistance(2.0)
      .requiresTool(false)
      .tagBlock('minecraft:mineable/pickaxe')

      event.create('titanium_machine_casing')
      .displayName('Titanium Machine Casing')
      .soundType('metal')
      .hardness(2.0)
      .resistance(2.0)
      .requiresTool(false)
      .tagBlock('minecraft:mineable/pickaxe')

      event.create('titanium_gear_casing')
      .displayName('Titanium Gear Casing')
      .soundType('metal')
      .hardness(2.0)
      .resistance(2.0)
      .requiresTool(false)
      .tagBlock('minecraft:mineable/pickaxe')

      event.create('titanium_machine_item_input')
      .soundType('metal')
      .hardness(2.0)
      .resistance(2.0)
      .requiresTool(false)
      .tagBlock('minecraft:mineable/pickaxe')

      event.create('titanium_machine_item_output')
      .soundType('metal')
      .hardness(2.0)
      .resistance(2.0)
      .requiresTool(false)
      .tagBlock('minecraft:mineable/pickaxe')

      event.create('titanium_logistic_casing')
      .displayName('Titanium Logistic Casing')
      .soundType('metal')
      .hardness(2.0)
      .resistance(2.0)
      .requiresTool(false)
      .tagBlock('minecraft:mineable/pickaxe')

      event.create('titanium_fridge_controller')
      .displayName('Titanium Super Fridge Controller')
      .soundType('metal')
      .hardness(2.0)
      .resistance(2.0)
      .requiresTool(false)
      .tagBlock('minecraft:mineable/pickaxe')

      event.create('titanium_coil')
      .displayName('Titanium Coil')
      .soundType('metal')
      .hardness(2.0)
      .resistance(2.0)
      .requiresTool(false)
      .tagBlock('minecraft:mineable/pickaxe')

      event.create('titanium_crushing_machine')
      .displayName('Titanium Crushing Controller')
      .soundType('metal')
      .hardness(2.0)
      .resistance(2.0)
      .requiresTool(false)
      .tagBlock('minecraft:mineable/pickaxe')

      event.create('titanium_vent_casing')
      .displayName('Titanium Vent Casing')
      .soundType('metal')
      .hardness(2.0)
      .resistance(2.0)
      .requiresTool(false)
      .tagBlock('minecraft:mineable/pickaxe')

      event.create('titanium_cooling_casing')
      .displayName('Titanium Cooling Casing')
      .soundType('metal')
      .hardness(2.0)
      .resistance(2.0)
      .requiresTool(false)
      .tagBlock('minecraft:mineable/pickaxe')

      
      event.create('titanium_charging_machine_controller')
      .soundType('metal')
      .hardness(2.0)
      .resistance(2.0)
      .requiresTool(false)
      .tagBlock('minecraft:mineable/pickaxe')

            
      event.create('titanium_alloy_smelter_controller')
      .soundType('metal')
      .hardness(2.0)
      .resistance(2.0)
      .requiresTool(false)
      .tagBlock('minecraft:mineable/pickaxe')

      event.create('titanium_ore_crushing_machine')
      .soundType('metal')
      .hardness(2.0)
      .resistance(2.0)
      .requiresTool(false)
      .tagBlock('minecraft:mineable/pickaxe')

      event.create('titanium_stress_input')
      .soundType('metal')
      .hardness(2.0)
      .resistance(2.0)
      .requiresTool(false)
      .tagBlock('minecraft:mineable/pickaxe')

      event.create('titanium_machine_fluid_input')
      .soundType('metal')
      .hardness(2.0)
      .resistance(2.0)
      .requiresTool(false)
      .tagBlock('minecraft:mineable/pickaxe')

      event.create('titanium_machine_fluid_output')
      .soundType('metal')
      .hardness(2.0)
      .resistance(2.0)
      .requiresTool(false)
      .tagBlock('minecraft:mineable/pickaxe')

      event.create('titanium_energy_input')
      .soundType('metal')
      .hardness(2.0)
      .resistance(2.0)
      .requiresTool(false)
      .tagBlock('minecraft:mineable/pickaxe')

      

    })

    